; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

NotMe_Start
NotMe_StartDisarkGenerateExternalLabel

NotMe_DisarkByteRegionStart0
	db "AT20"
NotMe_DisarkPointerRegionStart1
	dw NotMe_ArpeggioTable	; The address of the Arpeggio table.
	dw NotMe_PitchTable	; The address of the Pitch table.
	dw NotMe_InstrumentTable	; The address of the Instrument table.
	dw NotMe_EffectBlockTable	; The address of the Effect Block table.
NotMe_DisarkPointerRegionEnd1


; The addresses of each Subsong:
NotMe_DisarkPointerRegionStart2
	dw NotMe_Subsong0_Start
NotMe_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
NotMe_ArpeggioTable
NotMe_DisarkPointerRegionStart3
NotMe_DisarkPointerRegionEnd3

; Declares all the Pitches.
NotMe_PitchTable
NotMe_DisarkPointerRegionStart4
NotMe_DisarkPointerRegionEnd4

; Declares all the Instruments.
NotMe_InstrumentTable
NotMe_DisarkPointerRegionStart5
	dw NotMe_EmptyInstrument
	dw NotMe_Instrument1
NotMe_DisarkPointerRegionEnd5

NotMe_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
NotMe_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

NotMe_Instrument1
	db 5	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
NotMe_EffectBlockTable
NotMe_DisarkPointerRegionStart6
	dw NotMe_EffectBlock_P4P2	; Index 0
NotMe_DisarkPointerRegionEnd6

NotMe_EffectBlock_P4P2
	db 4, 2

NotMe_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
NotMe_Subsong0_DisarkByteRegionStart0
NotMe_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 7	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 12	; Base note index (>=0).

NotMe_Subsong0_Linker
NotMe_Subsong0_DisarkPointerRegionStart1
; Position 0
NotMe_Subsong0_Linker_Loop
	dw NotMe_Subsong0_Track0
	dw NotMe_Subsong0_Track1
	dw NotMe_Subsong0_Track2
	dw NotMe_Subsong0_LinkerBlock0

; Position 1
	dw NotMe_Subsong0_Track3
	dw NotMe_Subsong0_Track4
	dw NotMe_Subsong0_Track2
	dw NotMe_Subsong0_LinkerBlock1

; Position 2
	dw NotMe_Subsong0_Track5
	dw NotMe_Subsong0_Track6
	dw NotMe_Subsong0_Track2
	dw NotMe_Subsong0_LinkerBlock1

; Position 3
	dw NotMe_Subsong0_Track7
	dw NotMe_Subsong0_Track8
	dw NotMe_Subsong0_Track2
	dw NotMe_Subsong0_LinkerBlock1

; Position 4
	dw NotMe_Subsong0_Track9
	dw NotMe_Subsong0_Track10
	dw NotMe_Subsong0_Track2
	dw NotMe_Subsong0_LinkerBlock1

; Position 5
	dw NotMe_Subsong0_Track11
	dw NotMe_Subsong0_Track12
	dw NotMe_Subsong0_Track2
	dw NotMe_Subsong0_LinkerBlock1

; Position 6
	dw NotMe_Subsong0_Track13
	dw NotMe_Subsong0_Track14
	dw NotMe_Subsong0_Track2
	dw NotMe_Subsong0_LinkerBlock1

; Position 7
	dw NotMe_Subsong0_Track15
	dw NotMe_Subsong0_Track16
	dw NotMe_Subsong0_Track2
	dw NotMe_Subsong0_LinkerBlock1

NotMe_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
NotMe_Subsong0_DisarkWordForceReference2
	dw NotMe_Subsong0_Linker_Loop

NotMe_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
NotMe_Subsong0_DisarkWordForceReference3
	dw NotMe_Subsong0_SpeedTrack0	; SpeedTrack address.
NotMe_Subsong0_DisarkWordForceReference4
	dw NotMe_Subsong0_EventTrack0	; EventTrack address.
NotMe_Subsong0_LinkerBlock1
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
NotMe_Subsong0_DisarkWordForceReference5
	dw NotMe_Subsong0_SpeedTrack1	; SpeedTrack address.
NotMe_Subsong0_DisarkWordForceReference6
	dw NotMe_Subsong0_EventTrack0	; EventTrack address.

NotMe_Subsong0_Track0
	db 247
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 47
	db 48
	db 50
	db 60	; Waits for 1 line.

	db 53
	db 52
	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 53
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track1
	db 235
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 45
	db 43
	db 60	; Waits for 1 line.

	db 41
	db 45
	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track2
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track3
	db 180
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 47
	db 50
	db 60	; Waits for 1 line.

	db 50
	db 52
	db 48
	db 60	; Waits for 1 line.

	db 48
	db 45
	db 48
	db 60	; Waits for 1 line.

	db 48
	db 50
	db 47
	db 60	; Waits for 1 line.

	db 47
	db 43
	db 47
	db 60	; Waits for 1 line.

	db 47
	db 48
	db 45
	db 60	; Waits for 1 line.

	db 45
	db 41
	db 45
	db 60	; Waits for 1 line.

	db 48
	db 47
	db 45
	db 43
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track4
	db 176
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 53
	db 50
	db 60	; Waits for 1 line.

	db 50
	db 47
	db 48
	db 60	; Waits for 1 line.

	db 48
	db 52
	db 48
	db 60	; Waits for 1 line.

	db 48
	db 45
	db 47
	db 60	; Waits for 1 line.

	db 47
	db 50
	db 47
	db 60	; Waits for 1 line.

	db 47
	db 43
	db 45
	db 60	; Waits for 1 line.

	db 45
	db 48
	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 41
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track5
	db 171
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 52
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 48
	db 47
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 50
	db 52
	db 60	; Waits for 1 line.

	db 55
	db 61, 6	; Waits for 7 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track6
	db 171
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 45
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 48
	db 50
	db 60	; Waits for 1 line.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 61, 6	; Waits for 7 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track7
	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 52
	db 50
	db 47
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track8
	db 178
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track9
	db 175
	db 1	; New Instrument (1).
	db 50
	db 48
	db 60	; Waits for 1 line.

	db 43
	db 45
	db 47
	db 60	; Waits for 1 line.

	db 48
	db 47
	db 45
	db 60	; Waits for 1 line.

	db 47
	db 45
	db 43
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 52
	db 50
	db 47
	db 47
	db 50
	db 48
	db 60	; Waits for 1 line.

	db 43
	db 45
	db 47
	db 60	; Waits for 1 line.

	db 48
	db 47
	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track10
	db 171
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 43
	db 61, 6	; Waits for 7 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track11
	db 176
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 45
	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 45
	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track12
	db 176
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 48
	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 48
	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track13
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 178
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 52
	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 47
	db 45
	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track14
	db 171
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 41
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 45
	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 48
	db 50
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track15
	db 178
	db 1	; New Instrument (1).
	db 53
	db 50
	db 60	; Waits for 1 line.

	db 48
	db 52
	db 48
	db 60	; Waits for 1 line.

	db 47
	db 50
	db 47
	db 60	; Waits for 1 line.

	db 45
	db 48
	db 45
	db 60	; Waits for 1 line.

	db 43
	db 47
	db 43
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 61, 127	; Waits for 128 lines.


NotMe_Subsong0_Track16
	db 178
	db 1	; New Instrument (1).
	db 47
	db 50
	db 60	; Waits for 1 line.

	db 48
	db 45
	db 48
	db 60	; Waits for 1 line.

	db 47
	db 43
	db 47
	db 60	; Waits for 1 line.

	db 45
	db 41
	db 45
	db 60	; Waits for 1 line.

	db 43
	db 40
	db 43
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


; The speed tracks
NotMe_Subsong0_SpeedTrack0
	db 22	; Value: 11.
	db 253	; Wait for 127 lines.
NotMe_Subsong0_SpeedTrack1
	db 255	; Wait for 128 lines.

; The event tracks
NotMe_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

NotMe_Subsong0_DisarkByteRegionEnd0
